#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_go_Darwin="https://storage.googleapis.com/golang/go${GO_VERSION}.darwin-amd64.tar.gz"
  local url_go_Linux="https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz"

  local url_go="url_go_$(uname -s)"
  local fnm_go="$(basename "${!url_go}")"
  cache curl "$fnm_go" "${!url_go}"

  localhost -m file -- state=directory dest="$shome/install"
  pushd "$shome/install"
  rm -rf go
  tar xfz "${CACHE_DIR}/curl/$fnm_go"
  popd

  export GOPATH="$shome/install"
  go get -u github.com/golang/dep/...
  localhost -m file -- state=directory dest="$shome/bin"
  localhost -m file -- state=link src=../install/bin/dep dest="$shome/bin/dep"
}

bootstrap
