#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_go_Darwin='https://storage.googleapis.com/golang/go1.5.3.darwin-amd64.tar.gz'
  local url_go_Linux='https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz'

  local url_go="url_go_$(uname -s)"
  local fnm_go="$(basename "$url_go")"
  cache curl "$fnm_go" "${!url_go}" -sS -L

  mkdir -p "$shome/install"
  pushd "$shome/install"
  tar xvfz "${BASEBOX_CACHE}/curl/$fnm_go"
  popd
}

bootstrap
