#!/usr/bin/env bash

function _go_profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && echo "$PWD")"
  PATH="$shome/bin:$shome/install/go/bin:$PATH"

  export GOROOT="${GOROOT:-"$shome/install/go"}"
}

_go_profile
