#!/usr/bin/env bash

function main {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && echo "$PWD")"
  source "$shome/script/profile"

  if [[ -x "$(type -P go)" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"

