#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_go="$(go version 2>&- | awk 'NR == 1 {print $3}' | perl -pe 's{^go}{}' || true)"
  jq -n --arg go "$ver_go" '{go: $go}'
}

version "$@"
